version: 2

defaults: &defaults
  working_directory: ~/sr-app
  docker:
    - image: circleci/node:8

restore_modules_cache: &restore_modules_cache
  restore_cache:
    keys:
    - sr-app-{{ checksum "yarn.lock" }}
    # fallback to using the latest cache if no exact match is found
    - sr-app-


jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Installing Dependencies
          command: yarn install
      - save_cache:
          key: sr-app-{{ checksum "yarn.lock" }}
          paths: node_modules
      - run:
          name: Remove node_modules to cleanup workspace
          command: rm -rf node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Running tests and checks
          command: yarn test
      - run:
          name: Sending test coverage to CodeCov
          command: bash <(curl -s https://codecov.io/bash)

  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Creating distributable files
          command: echo ok
      - store_artifacts:
          path: dist
          destination: sr-app

  publish:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Trying to deploy
          command: yarn start release

workflows:
  version: 2
  automated:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          filters:
            branches:
              only: master
          requires:
            - test
      - publish:
          filters:
            branches:
              only: master
          requires:
            - build
          context: org-global
